stroopwafelshop:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: oauth
      project: xd-analytics-engineers
      dataset: stroopwafelshop
      threads: 3
      timeout_seconds: 300
      location: EU
      priority: interactive
